application: coe2043-team-1
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: assets

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: modulethree.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
